apiVersion: batch/v1
kind: Job
metadata:
  name: provision
  namespace: default
spec:
  activeDeadlineSeconds: 240
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: provision
        image: quay.io/gravitational/provisioner:XXX_PROVISIONER_VERSION_XXX
        imagePullPolicy: Always
        args: ['cluster-provision']
        volumeMounts:
        - mountPath: /mnt/state
          name: state-volume
      volumes:
      - name: state-volume
        emptyDir: {}
